name: flutter_first_test
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


  custom_widgets:
    path: custom_widgets/

  jd_address_selector:
    path: jd_address_selector/
  package_info: ^0.4.0+6

  # banner
  flutter_swiper: ^1.1.6

  # 时间线 https://github.com/furkantektas/timeline_list
  timeline_list: ^0.0.5

  # 视频播放器器
  video_player: ^0.10.2


  # 图片选择器
  image_picker: ^0.6.1+4

  #
  rounded_letter: ^0.0.6

  contact_picker: ^0.0.2

  # 瀑布流
  flutter_staggered_grid_view: ^0.3.0
  #  评分
  clippy_flutter: ^1.1.0
  #  调色板
  palette_generator: ^0.2.0
  url_launcher: ^5.1.2
#  城市选择
  city_picker: ^0.1.4
#  ios 城市选择
  city_pickers: ^0.1.25
  # 设备信息
  device_info: ^0.4.0+2

  # 扫描二维码
  barcode_scan: ^1.0.0
  # flutter 生成二维码
  qr_flutter: ^3.0.1
  # 图表
  charts_flutter: ^0.8.0
  # 侧滑菜单
  flutter_inner_drawer: ^0.4.0
  # 颜色选择器
  flutter_colorpicker: ^0.2.6

  # 刷新加载控件
  flutter_easyrefresh: ^2.0.4
  # 滑动视差效果图片 https://github.com/pulyaevskiy/parallax-image
  parallax_image: ^0.3.1
  #  定位
  amap_base_location: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - images/3eerwrew.png
    - images/timg.jpeg
    - images/test1.jpg
    - images/ic_share.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
